name: Run Playwright Tests

on:
  schedule:
    - cron: '*/1 * * * *' # 매분 실행

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Make script executable
        run: chmod +x lottoBot.spec.js

      - name: Run Playwright Tests
        run: npx playwright test