name: Run Playwright every minute

on:
  schedule:
    - cron: '*/1 * * * *' # 매일 1분마다 실행

jobs:
  playwright:
    runs-on: ubuntu-latest # 원하는 운영체제 선택

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18 # 사용할 Node.js 버전을 18로 선택

    - name: Install dependencies
      run: npm install

    - name: Make 'folio' executable
      run: chmod +x /node_modules/folio

    - name: Run Playwright
      run: npx folio