name: Run Playwright Tests

on:
  schedule:
    - cron: '*/10 * * * *' # 매분 실행

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14  # Node.js 버전을 적절한 버전으로 변경 18안됨

      - name: Install dependencies
        run: npm install

      - name: Make script executable
        run: chmod +x lottoBot.spec.js

      - name: Install Playwright and browsers
        run: npx playwright install

      - name: Run Playwright Tests
        run: npx playwright test